// DO NOT EDIT DIRECTLY. Autogenerated 2023-8-12 09:56:49

export const fonts = {
  sans: 'Inter, sans-serif',
  mono: 'JetBrains Mono, monospace',
};

export const radii = {
  small: '2px',
  medium: '4px',
  full: '999px',
};

export const sizes = {
  1: '2px',
  2: '4px',
  3: '8px',
  4: '12px',
  5: '16px',
  6: '24px',
  7: '32px',
  8: '48px',
  10: '28px',
  controlMedium: '28px',
  dropdownMaxHeight: '45vh',
  scrollbarWidth: '8px',
};

export const space = {
  1: '2px',
  2: '4px',
  3: '8px',
  4: '12px',
  5: '16px',
  6: '24px',
  7: '32px',
  8: '48px',
  9: '64px',
};

export const fontWeights = {
  normal: '400',
  bold: '500',
};

export const fontSizes = {
  xxsmall: '10px',
  xsmall: '11px',
  small: '12px',
  medium: '13px',
  large: '16px',
};
