export enum BackgroundJobs {
  NODEMANAGER_UPDATE = 'nodemanager_update',
  NODEMANAGER_FINDNODESWITHDATA = 'nodemanager_findnodeswithdata',
  PLUGIN_UPDATEPLUGINDATA = 'plugindata_updateplugindata',
  PLUGIN_UPDATENODES = 'plugin_updatenodes',
  PLUGIN_REMOVE_RELAUNCH_DATA = 'plugin_remove_relaunch_data',
  UI_APPLYNODEVALUE = 'ui_applynodevalue',
  UI_PULLTOKENS = 'ui_pulltokens',
  UI_EDITSINGLETOKEN = 'ui_editsingltoken',
  UI_CREATESINGLETOKEN = 'ui_createsingletoken',
  UI_DUPLICATETOKEN = 'ui_duplicatetoken',
  UI_DELETETOKEN = 'ui_deletetoken',
  UI_DELETETOKENGROUP = 'ui_deletetokengroup',
  UI_RENAMETOKENGROUP = 'ui_renametokengroup',
  UI_DUPLICATETOKENGROUP = 'ui_duplicatetokengroup',
  UI_FETCHTOKENSFROMFILE = 'ui_fetchtokensfromfile',
  UI_UNDOING = 'ui_undoing',
  UI_REDOING = 'ui_redoing',
  UI_ATTACHING_LOCAL_STYLES = 'ui_attaching_local_styles',
  UI_ATTACHING_LOCAL_VARIABLES = 'ui_attaching_local_variables',
  UI_RENAME_TOKEN_ACROSS_SETS = 'ui_rename_token_across_sets',
  UI_CREATEVARIABLES = 'ui_create_variables',
  UI_CREATE_STYLES = 'ui_create_styles',
  UI_CREATE_LIVING_DOCUMENTATION = 'ui_create_living_documentation',
}
