export enum BlendColorModifierTypes {
  MIX = 'mix',
  MULTIPLY = 'multiply',
  SCREEN = 'screen',
  OVERLAY = 'overlay',
  COLOR_DODGE = 'color-dodge',
  COLOR_BURN = 'color-burn',
  HARD_LIGHT = 'hard-light',
  SOFT_LIGHT = 'soft-light',
  DIFFERENCE = 'difference',
  EXCLUSION = 'exclusion',
  HUE = 'hue',
  SATURATION = 'saturation',
  COLOR = 'color',
  LUMINOSITY = 'luminosity',
  ADD = 'add',
  SUBTRACT = 'subtract',
}

export enum SingleColorModifierTypes {
  LIGHTEN = 'lighten',
  DARKEN = 'darken',
  ALPHA = 'alpha',
  LUMINANCE = 'luminance',
}

export enum ColorModifierTypes {
  LIGHTEN = 'lighten',
  DARKEN = 'darken',
  ALPHA = 'alpha',
  LUMINANCE = 'luminance',
  MIX = 'mix',
  MULTIPLY = 'multiply',
  SCREEN = 'screen',
  OVERLAY = 'overlay',
  COLOR_DODGE = 'color-dodge',
  COLOR_BURN = 'color-burn',
  HARD_LIGHT = 'hard-light',
  SOFT_LIGHT = 'soft-light',
  DIFFERENCE = 'difference',
  EXCLUSION = 'exclusion',
  HUE = 'hue',
  SATURATION = 'saturation',
  COLOR = 'color',
  LUMINOSITY = 'luminosity',
  ADD = 'add',
  SUBTRACT = 'subtract',
}
