'use strict';
exports.__esModule = true;
exports.TokenTypes = void 0;
var TokenTypes;
(function (TokenTypes) {
  TokenTypes['OTHER'] = 'other';
  TokenTypes['COLOR'] = 'color';
  TokenTypes['IMPLICIT'] = 'implicit';
  TokenTypes['BORDER_RADIUS'] = 'borderRadius';
  TokenTypes['SIZING'] = 'sizing';
  TokenTypes['SPACING'] = 'spacing';
  TokenTypes['TEXT'] = 'text';
  TokenTypes['TYPOGRAPHY'] = 'typography';
  TokenTypes['OPACITY'] = 'opacity';
  TokenTypes['BORDER_WIDTH'] = 'borderWidth';
  TokenTypes['BOX_SHADOW'] = 'boxShadow';
  TokenTypes['FONT_FAMILIES'] = 'fontFamilies';
  TokenTypes['FONT_WEIGHTS'] = 'fontWeights';
  TokenTypes['LINE_HEIGHTS'] = 'lineHeights';
  TokenTypes['FONT_SIZES'] = 'fontSizes';
  TokenTypes['LETTER_SPACING'] = 'letterSpacing';
  TokenTypes['PARAGRAPH_SPACING'] = 'paragraphSpacing';
  TokenTypes['TEXT_DECORATION'] = 'textDecoration';
  TokenTypes['TEXT_CASE'] = 'textCase';
})((TokenTypes = exports.TokenTypes || (exports.TokenTypes = {})));
