export const mockShowUI: jest.Mock;
export const dispatchFigmaEvent: jest.Mock;
export const mockOn: jest.Mock;
export const mockGetAsync: jest.Mock;
export const mockSetAsync: jest.Mock;
export const mockNotify: jest.Mock;
export const mockUiPostMessage: jest.Mock;
export const mockGetLocalPaintStyles: jest.Mock;
export const mockGetLocalTextStyles: jest.Mock;
export const mockGetLocalEffectStyles: jest.Mock;
export const mockLoadFontAsync: jest.Mock;
export const mockCreateTextStyle: jest.Mock;
export const mockCreatePaintStyle: jest.Mock;
export const mockCreateEffectStyle: jest.Mock;
export const mockGetStyleById: jest.Mock;
export const mockImportStyleByKeyAsync: jest.Mock;
export const mockUiOn: jest.Mock;
export const mockCodegenOn: jest.Mock;
export const mockRootSetSharedPluginData: jest.Mock;
export const mockRootGetSharedPluginData: jest.Mock;
export const mockGetNodeById: jest.Mock;
export const mockScrollAndZoomIntoView: jest.Mock;
export const mockCreateImage: jest.Mock;
export const mockGetLocalVariables: jest.Mock;
export const mockGetLocalVariablesAsync: jest.Mock;
export const mockCreateVariable: jest.Mock;
export const mockGetLocalVariableCollections = jest.Mock;
export const mockGetLocalVariableCollectionsAsync = jest.Mock;
export const mockCreateVariableCollection = jest.Mock;
export const mockImportVariableByKeyAsync = jest.Mock;
export const mockGetVariableById = jest.Mock;
export const mockSetValueForMode = jest.Mock;
export const mockSetBoundVariableForPaint = jest.Mock;
export const mockCreateVariableCollection = jest.Mock;