export default {
    borderRadius: [
        'borderRadius',
        'borderRadiusTopLeft',
        'borderRadiusTopRight',
        'borderRadiusBottomRight',
        'borderRadiusBottomLeft',
    ],
    spacing: ['spacing', 'verticalPadding', 'horizontalPadding', 'itemSpacing'],
    sizing: ['height', 'width'],
    colors: ['fill', 'border'],
    opacity: ['opacity'],
    borderWidth: ['borderWidth'],
    boxShadow: ['boxShadow'],
    typography: ['typography'],
    lineHeights: ['lineHeights'],
    fontSizes: ['fontSizes'],
    fontFamilies: ['fontFamilies'],
    values: {},
    fontWeights: {},
};
