export default {
    borderRadius: [
        'borderRadius',
        'borderRadiusTopLeft',
        'borderRadiusTopRight',
        'borderRadiusBottomRight',
        'borderRadiusBottomLeft',
    ],
    spacing: ['spacing', 'verticalPadding', 'horizontalPadding', 'itemSpacing'],
    sizing: ['height', 'width'],
    colors: ['fill', 'border'],
    opacity: ['opacity'],
    borderWidth: ['borderWidth'],
    typography: ['typography'],
    lineHeights: ['lineHeights'],
    fontSizes: ['fontSizes'],
    fontFamilies: ['fontFamilies'],

    values: {},
    fontFamilies: {},
    fontWeights: {},
    fontSizes: {},
    lineHeights: {},
    typography: {},
};
