export default {
    borderRadius: [
        'borderRadius',
        'borderRadiusTopLeft',
        'borderRadiusTopRight',
        'borderRadiusBottomRight',
        'borderRadiusBottomLeft',
    ],
    spacing: [
        'spacing',
        'verticalPadding',
        'horizontalPadding',
        'itemSpacing',
        'paddingLeft',
        'paddingRight',
        'paddingTop',
        'paddingBottom',
    ],
    sizing: ['height', 'width'],
    colors: ['fill', 'border'],
    opacity: ['opacity'],
    borderWidth: ['borderWidth'],
    typography: ['typography'],
    lineHeights: ['lineHeights'],
    fontSizes: ['fontSizes'],
    fontFamilies: ['fontFamilies'],
    values: {},
    fontWeights: {},
};
