name: Cleanup Preview Deployments

on:
  pull_request:
    types: [closed]
  schedule:
    # Run cleanup weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Cleanup closed PR previews
        run: |
          # Get list of open PRs
          OPEN_PRS=$(gh pr list --state open --json number --jq '.[].number' || echo "")
          
          # Find all pr-* directories
          PR_DIRS=$(find . -maxdepth 1 -type d -name "pr-*" | sed 's|./||' || echo "")
          
          # Remove directories for closed PRs
          for dir in $PR_DIRS; do
            PR_NUM=$(echo "$dir" | sed 's/pr-//')
            if [[ ! "$OPEN_PRS" =~ $PR_NUM ]]; then
              echo "Removing preview for closed PR #$PR_NUM"
              rm -rf "$dir"
            else
              echo "Keeping preview for open PR #$PR_NUM"
            fi
          done
          
          # Update index page with remaining PRs
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Preview Deployments</title>
            <meta charset="utf-8">
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; }
              .container { max-width: 800px; margin: 0 auto; }
              .pr-link { display: block; padding: 12px 16px; margin: 8px 0; background: #f6f8fa; border-radius: 6px; text-decoration: none; color: #24292f; border: 1px solid #d0d7de; }
              .pr-link:hover { background: #f3f4f6; }
              .pr-number { font-weight: 600; color: #0969da; }
              .no-previews { color: #656d76; font-style: italic; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>🎨 Tokens Studio Preview Deployments</h1>
              <p>Preview deployments for open pull requests of the Tokens Studio Figma Plugin.</p>
          EOF
          
          # Add links for remaining PR directories
          REMAINING_DIRS=$(find . -maxdepth 1 -type d -name "pr-*" | sed 's|./||' | sort -V || echo "")
          if [ -z "$REMAINING_DIRS" ]; then
            echo '<p class="no-previews">No active previews at the moment.</p>' >> index.html
          else
            for dir in $REMAINING_DIRS; do
              PR_NUM=$(echo "$dir" | sed 's/pr-//')
              # Get PR title from GitHub API
              PR_TITLE=$(gh pr view "$PR_NUM" --json title --jq '.title' 2>/dev/null || echo "Pull Request #$PR_NUM")
              echo "<a href=\"$dir/\" class=\"pr-link\">" >> index.html
              echo "<span class=\"pr-number\">#$PR_NUM</span>" >> index.html
              echo "$PR_TITLE" >> index.html
              echo "</a>" >> index.html
            done
          fi
          
          cat >> index.html << 'EOF'
            </div>
          </body>
          </html>
          EOF
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Cleanup preview deployments for closed PRs"
            git push
          else
            echo "No changes to commit"
          fi